### ISSUE TITLE
cannot move config file because it is not found

### ISSUE THREAD

**Issue by Rohithgarde** [mbits-mirafra/neovim#7]
<img width="403" alt="image" src="https://github.com/mbits-mirafra/neovim/assets/102989131/5a3c775b-fcfa-484e-a0bd-f245915f128c">

**Comment by Myron2812** [comment]
This step is done to ensure that any previous nvim configurations don't conflict with the new configuration. I've added instructions explicitly stating that this needs to be done only if a config file exists. Let me know if the issue persists. Closing the issue for now. 👍
